version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    container_name: lab4_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab4db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: lab4_backend
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: lab4db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: lab4_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
